### ISSUE TITLE
backup from emoncms.org fails to add feeds to feeds table

### ISSUE THREAD

**Issue by martynwendon** [emoncms/usefulscripts#24]
When running backup.php against emoncms.org all feed data is pulled down correctly and inputs are created, but feeds aren't (i.e. feeds table is empty).

Adding some cursory debug echo's to lib/metadata.php show's it's trying to execute:

INSERT INTO feeds (id,userid,name,tag,datatype,public,size,engine) VALUES ('175174','1','Total Use','Node:9999','1','','30622220','5')

This fails because "public" doesn't have a data value, as can be seen from trying to run the statement manually in mysql:

INSERT INTO feeds (id,userid,name,tag,datatype,public,size,engine) VALUES ('393361','1','Battery Store Charge Solar PV Savings Daily','Node:72','2','','1233','2');

ERROR 1366 (22007): Incorrect integer value: '' for column `oem`.`feeds`.`public` at row 1

For my use case I fixed it by hard coding "0" for public in the lib/metadata.php

I didn't investigate further, but it would appear that public value isn't sent correctly in the data pulled from emoncms.org, or it's lost somewhere along the way.

**Comment by TrystanLea** [comment]
Cheers @martynwendon I've added a check to fix this, taking a similar approach to your description https://github.com/emoncms/usefulscripts/commit/ed7f3d526632db6062fb83b15906e3f021816e18
